name: Tia Carrere
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68199
title: Tia Carrere is an American actress and Grammy Award winning singer.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cf976e'
    - '#703511'
    - '#a46030'
    - '#7f7b69'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
