name: Tia Carrere
favicon: null
layout_spectrum: 0.08654
typography_spectrum: 0.20222
title: 'Tia Carrere is an American actress, songwriter, film producer and actress.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cf976e'
    - '#703511'
    - '#a46030'
    - '#7f7b69'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
