name: Tia Carrere
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68199
title: Tia Carrere is an American actress and Grammy Award winning singer.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020203'
    - '#ff3f49'
    - '#ffbb70'
    - '#7592c4'
    - '#de7963'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
