name: Tia Carrere
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68199
title: Tia Carrere is an American actress and Grammy Award winning singer.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a39d92'
    - '#ffffff'
    - '#cdd1ca'
    - '#86532d'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
